"use client";

import { useEffect, useMemo, useState } from "react";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  AreaChart,
  Area,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
} from "recharts";

// ─── /backtest ──────────────────────────────────────────────────────────────
// Investor-grade view of the REAL walk-forward out-of-sample backtest. Data is
// generated by zentory_algo/build_backtest_json.py from the committed results/
// (no fitting in the browser). Honesty is the product: the edge is drawdown
// reduction, NOT guaranteed profit — and XRP underperforms on return, shown.

const GOLD = "#B08D57";
const GRAY = "#8A8F98";
const RED = "#C2353F";
const TEXT = "#eaeaea";
const ASSETS = ["BTC", "ETH", "SOL", "XRP"] as const;
type Asset = (typeof ASSETS)[number];

type Stat = {
  cagr: number; totalReturn: number; sharpe: number; sortino: number;
  maxDd: number; calmar: number; annVol: number;
};
type AssetData = {
  oosStart: string; oosEnd: string; nFolds: number; frozenSpec: string;
  avgExposure: number; drawdownWins: number; sortinoWins: number;
  strategy: Stat; hold: Stat;
  yearly: { strat: Record<string, number>; hold: Record<string, number> };
  curve: { t: string; s: number; h: number }[];
  drawdown: { t: string; s: number; h: number }[];
  costSensitivity: { bps: number; stratSortino: number; holdSortino: number; stratCagr: number; holdCagr: number; stratMaxDd: number }[];
};
type Backtest = {
  costBpsPerSide: number; cadence: string; note: string;
  assets: Record<string, AssetData>;
};

const fmtPct = (x: number, d = 0) => `${x >= 0 ? "+" : ""}${(x * 100).toFixed(d)}%`;
const fmtX = (x: number) => `${x.toFixed(1)}×`;

function MetricCard({ label, strat, hold, fmt, betterHigh = true, sub }: {
  label: string; strat: number; hold: number; fmt: (n: number) => string; betterHigh?: boolean; sub?: string;
}) {
  const stratWins = betterHigh ? strat >= hold : strat <= hold;
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
      <div className="text-[11px] uppercase tracking-wider mb-2" style={{ color: "rgba(234,234,234,0.45)" }}>{label}</div>
      <div className="flex items-baseline gap-2">
        <span className="text-2xl font-bold tabular-nums" style={{ color: stratWins ? "#34d399" : RED }}>{fmt(strat)}</span>
        <span className="text-xs" style={{ color: "rgba(234,234,234,0.4)" }}>strategy</span>
      </div>
      <div className="flex items-baseline gap-2 mt-1">
        <span className="text-base font-medium tabular-nums" style={{ color: "rgba(234,234,234,0.6)" }}>{fmt(hold)}</span>
        <span className="text-xs" style={{ color: "rgba(234,234,234,0.4)" }}>holding</span>
      </div>
      {sub && <div className="text-[10px] mt-2" style={{ color: "rgba(234,234,234,0.4)" }}>{sub}</div>}
    </div>
  );
}

export default function BacktestPage() {
  const [data, setData] = useState<Backtest | null>(null);
  const [error, setError] = useState(false);
  const [asset, setAsset] = useState<Asset>("BTC");

  useEffect(() => {
    fetch("/backtest.json", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((j: Backtest) => setData(j))
      .catch(() => setError(true));
  }, []);

  const a = data?.assets[asset];

  const eqDomain = useMemo<[number, number]>(() => {
    if (!a) return [0.5, 25];
    const vals = a.curve.flatMap((p) => [p.s, p.h]).filter((v) => v > 0);
    return [Math.max(0.1, Math.min(...vals) * 0.85), Math.max(...vals) * 1.15];
  }, [a]);

  const yearlyData = useMemo(() => {
    if (!a) return [];
    const years = Array.from(new Set([...Object.keys(a.yearly.strat), ...Object.keys(a.yearly.hold)])).sort();
    return years.map((y) => ({ year: y, strat: (a.yearly.strat[y] ?? 0), hold: (a.yearly.hold[y] ?? 0) }));
  }, [a]);

  return (
    <div className="space-y-10 pb-16">
      <header className="space-y-3">
        <h1 className="text-4xl font-bold tracking-tight" style={{ color: TEXT }}>Backtest & Historical Performance</h1>
        <p className="text-sm max-w-3xl" style={{ color: "rgba(234,234,234,0.6)" }}>
          A <strong style={{ color: TEXT }}>walk-forward out-of-sample</strong> backtest across ~6 years of 4-hour data.
          Each fold trades only on data <em>after</em> its training window — there is no peeking at the future.
          And there are <strong style={{ color: TEXT }}>no fitted parameters</strong>: the target exposure is the
          average long/flat vote across the entire trend + volatility-gate family, so in-sample equals
          out-of-sample by construction. That is the opposite of curve-fitting — it is why these numbers should
          survive contact with live markets.
        </p>
      </header>

      {error && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6 text-sm" style={{ color: "rgba(234,234,234,0.8)" }}>
          Couldn&apos;t load <code className="text-xs">/backtest.json</code> — retry shortly.
        </div>
      )}

      {/* Honest decomposition — the most important section */}
      <section className="rounded-2xl border p-6 space-y-3" style={{ borderColor: `${GOLD}55`, background: `${GOLD}0d` }}>
        <h2 className="text-lg font-semibold" style={{ color: GOLD }}>Where the edge comes from — read this first</h2>
        <p className="text-sm leading-relaxed" style={{ color: "rgba(234,234,234,0.75)" }}>
          The strategy&apos;s advantage is <strong style={{ color: TEXT }}>drawdown reduction</strong>, not a magic return.
          It stays invested in uptrends and rotates to cash in downtrends, so it sidesteps the worst of each crash —
          across every asset it cut the maximum loss roughly in half. That is the &ldquo;profit&rdquo; you see in the
          live tracker: when the asset falls and the strategy is in cash, it is <em>ahead by the loss it avoided</em>,
          not by trading gains.
        </p>
        <p className="text-sm leading-relaxed" style={{ color: "rgba(234,234,234,0.75)" }}>
          On <strong style={{ color: TEXT }}>absolute return</strong> the picture is honest and mixed: out-of-sample,
          BTC, ETH and SOL also <em>beat</em> holding, while <strong style={{ color: TEXT }}>XRP underperformed holding
          on return</strong> and won only on drawdown. No leverage, no shorts — so in a straight parabolic bull run,
          simply holding can win. We show every asset, including the one where we lose.
        </p>
      </section>

      {/* Asset tabs */}
      <div className="flex flex-wrap gap-2">
        {ASSETS.map((x) => (
          <button
            key={x}
            onClick={() => setAsset(x)}
            className="px-5 py-2 rounded-xl text-sm font-semibold uppercase tracking-wider transition-all"
            style={asset === x
              ? { background: GOLD, color: "#0b0b0d" }
              : { background: "rgba(255,255,255,0.04)", color: "rgba(234,234,234,0.7)", border: "1px solid rgba(255,255,255,0.1)" }}
          >
            {x}
          </button>
        ))}
      </div>

      {a && (
        <>
          <div className="text-xs" style={{ color: "rgba(234,234,234,0.5)" }}>
            Out-of-sample {a.oosStart} → {a.oosEnd} · {a.nFolds} folds · avg exposure {(a.avgExposure * 100).toFixed(0)}%
            (in market) · spec <code>{a.frozenSpec}</code> · {data?.costBpsPerSide} bps/side costs
          </div>

          {/* Metric cards */}
          <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <MetricCard label="Max Drawdown" strat={a.strategy.maxDd} hold={a.hold.maxDd} fmt={(n) => fmtPct(n, 0)} betterHigh sub={`${a.drawdownWins}/${a.nFolds} folds shallower than holding`} />
            <MetricCard label="CAGR (annualized)" strat={a.strategy.cagr} hold={a.hold.cagr} fmt={(n) => fmtPct(n, 0)} betterHigh />
            <MetricCard label="Sortino (downside risk-adj.)" strat={a.strategy.sortino} hold={a.hold.sortino} fmt={(n) => n.toFixed(2)} betterHigh />
            <MetricCard label="Calmar (return / max DD)" strat={a.strategy.calmar} hold={a.hold.calmar} fmt={(n) => n.toFixed(2)} betterHigh />
          </section>

          {/* Equity curve */}
          <section className="space-y-2">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Growth of $1 — out-of-sample (log scale)</h3>
            {/* Numeric heights: ResponsiveContainer height="100%" measures -1×-1
                in recharts 3.8 here ("width(-1) and height(-1)... greater than 0")
                and all three charts rendered EMPTY in production. */}
            <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
              <ResponsiveContainer width="100%" height={348}>
                <LineChart data={a.curve} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" />
                  <XAxis dataKey="t" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} minTickGap={48} />
                  <YAxis scale="log" domain={eqDomain} tickFormatter={fmtX} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown, n: unknown) => [fmtX(Number(v)), n === "s" ? "Strategy" : "Holding"]) as never}
                  />
                  <Legend formatter={(v) => (v === "s" ? "Strategy" : "Holding")} wrapperStyle={{ fontSize: 12 }} />
                  <Line type="monotone" dataKey="h" stroke={GRAY} dot={false} strokeWidth={1.5} isAnimationActive={false} />
                  <Line type="monotone" dataKey="s" stroke={GOLD} dot={false} strokeWidth={2} isAnimationActive={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Underwater / drawdown */}
          <section className="space-y-2">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Drawdown — how deep underwater (the real edge)</h3>
            <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
              <ResponsiveContainer width="100%" height={268}>
                <AreaChart data={a.drawdown} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" />
                  <XAxis dataKey="t" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} minTickGap={48} />
                  <YAxis tickFormatter={(v) => `${(v * 100).toFixed(0)}%`} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown, n: unknown) => [fmtPct(Number(v), 1), n === "s" ? "Strategy" : "Holding"]) as never}
                  />
                  <Legend formatter={(v) => (v === "s" ? "Strategy" : "Holding")} wrapperStyle={{ fontSize: 12 }} />
                  <Area type="monotone" dataKey="h" stroke={RED} fill={`${RED}22`} strokeWidth={1.2} isAnimationActive={false} />
                  <Area type="monotone" dataKey="s" stroke={GOLD} fill={`${GOLD}33`} strokeWidth={1.6} isAnimationActive={false} />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Per-year returns */}
          <section className="space-y-2">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Calendar-year returns — strategy vs holding</h3>
            <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
              <ResponsiveContainer width="100%" height={268}>
                <BarChart data={yearlyData} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                  <XAxis dataKey="year" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} />
                  <YAxis tickFormatter={(v) => `${(v * 100).toFixed(0)}%`} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown, n: unknown) => [fmtPct(Number(v), 1), n === "strat" ? "Strategy" : "Holding"]) as never}
                  />
                  <Legend formatter={(v) => (v === "strat" ? "Strategy" : "Holding")} wrapperStyle={{ fontSize: 12 }} />
                  <ReferenceLine y={0} stroke="rgba(255,255,255,0.2)" />
                  <Bar dataKey="hold" fill={GRAY} radius={[2, 2, 0, 0]} isAnimationActive={false} />
                  <Bar dataKey="strat" fill={GOLD} radius={[2, 2, 0, 0]} isAnimationActive={false} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Cost sensitivity */}
          {a.costSensitivity.length > 0 && (
            <section className="space-y-2">
              <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Cost sensitivity — does the edge survive fees?</h3>
              <p className="text-xs max-w-3xl" style={{ color: "rgba(234,234,234,0.55)" }}>
                We model {data?.costBpsPerSide} bps per side. The downside-risk edge (strategy Sortino minus holding)
                is real at realistic costs but erodes as fees climb — shown honestly so you can judge the margin.
              </p>
              <div className="overflow-x-auto rounded-2xl border border-white/10">
                <table className="w-full min-w-[560px] text-xs tabular-nums">
                  <thead>
                    <tr className="border-b border-white/10 text-left" style={{ color: "rgba(234,234,234,0.5)" }}>
                      {["Cost (bps/side)", "Strategy Sortino", "Holding Sortino", "Strategy CAGR", "Strategy max DD"].map((h) => (
                        <th key={h} className="px-4 py-3 font-medium uppercase tracking-wider">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody style={{ color: "rgba(234,234,234,0.75)" }}>
                    {a.costSensitivity.map((r) => {
                      const live = r.bps === (data?.costBpsPerSide ?? 5);
                      return (
                        <tr key={r.bps} className="border-b border-white/5" style={live ? { background: `${GOLD}14` } : undefined}>
                          <td className="px-4 py-2.5">{r.bps}{live ? "  ← modeled" : ""}</td>
                          <td className="px-4 py-2.5" style={{ color: r.stratSortino >= r.holdSortino ? "#34d399" : RED }}>{r.stratSortino.toFixed(2)}</td>
                          <td className="px-4 py-2.5">{r.holdSortino.toFixed(2)}</td>
                          <td className="px-4 py-2.5">{fmtPct(r.stratCagr, 0)}</td>
                          <td className="px-4 py-2.5">{fmtPct(r.stratMaxDd, 0)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </section>
          )}

          {/* Methodology */}
          <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6 space-y-2 text-sm" style={{ color: "rgba(234,234,234,0.7)" }}>
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Methodology & honest disclaimers</h3>
            <ul className="list-disc list-inside space-y-1.5">
              <li><strong style={{ color: TEXT }}>Walk-forward OOS:</strong> {a.nFolds} folds; every trade is on out-of-sample data after its training window.</li>
              <li><strong style={{ color: TEXT }}>No fitted parameters:</strong> exposure = mean long/flat vote over the whole trend+vol-gate grid, quantized to 25%. We deliberately do <em>not</em> hyper-optimize — that&apos;s how backtests lie.</li>
              <li><strong style={{ color: TEXT }}>Spot, long/flat only:</strong> no leverage, no shorts. Returns are in the underlying asset.</li>
              <li><strong style={{ color: TEXT }}>Costs:</strong> {data?.costBpsPerSide} bps per side modeled; see the cost-sensitivity table for the margin of safety.</li>
              <li><strong style={{ color: TEXT }}>Not a guarantee:</strong> a backtest is not live performance. Crypto can draw down {">"}40% even here. Past results do not predict the future.</li>
            </ul>
          </section>
        </>
      )}
    </div>
  );
}
