"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  ResponsiveContainer,
  LineChart,
  Line,
  AreaChart,
  Area,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
} from "recharts";

// ─── /backtest ──────────────────────────────────────────────────────────────
// Investor-grade view of the REAL walk-forward out-of-sample backtest. Data is
// generated by zentory_algo/build_backtest_json.py from the committed results/
// (no fitting in the browser). Honesty is the product: the edge is drawdown
// reduction, NOT guaranteed profit — and XRP underperforms on return, shown.

const GOLD = "#B08D57";
const GRAY = "#8A8F98";
const RED = "#C2353F";
const TEXT = "#eaeaea";
const ASSETS = ["BTC", "ETH", "SOL", "XRP"] as const;
type Asset = (typeof ASSETS)[number];

type Stat = {
  cagr: number; totalReturn: number; sharpe: number; sortino: number;
  maxDd: number; calmar: number; annVol: number;
};
type SatsBlock = {
  endSats: number; satsVsHold: number; maxDdSats: number; pctTimeAhead: number;
  curve: { t: string; x: number }[];
};
type AssetData = {
  oosStart: string; oosEnd: string; nFolds: number; frozenSpec: string;
  avgExposure: number; drawdownWins: number; sortinoWins: number;
  sats: SatsBlock;
  strategy: Stat; hold: Stat;
  yearly: { strat: Record<string, number>; hold: Record<string, number> };
  curve: { t: string; s: number; h: number }[];
  drawdown: { t: string; s: number; h: number }[];
  costSensitivity: { bps: number; stratSortino: number; holdSortino: number; stratCagr: number; holdCagr: number; stratMaxDd: number }[];
};
type Backtest = {
  costBpsPerSide: number; cadence: string; note: string;
  assets: Record<string, AssetData>;
};

const fmtPct = (x: number, d = 0) => `${x >= 0 ? "+" : ""}${(x * 100).toFixed(d)}%`;
const fmtX = (x: number) => `${x.toFixed(1)}×`;

function MetricCard({ label, strat, hold, fmt, betterHigh = true, sub }: {
  label: string; strat: number; hold: number; fmt: (n: number) => string; betterHigh?: boolean; sub?: string;
}) {
  const stratWins = betterHigh ? strat >= hold : strat <= hold;
  return (
    <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-5">
      <div className="text-[11px] uppercase tracking-wider mb-2" style={{ color: "#6a6f75" }}>{label}</div>
      <div className="flex items-baseline gap-2">
        <span className="text-2xl font-bold tabular-nums" style={{ color: stratWins ? "#34d399" : RED }}>{fmt(strat)}</span>
        <span className="text-xs" style={{ color: "#6a6f75" }}>strategy</span>
      </div>
      <div className="flex items-baseline gap-2 mt-1">
        <span className="text-base font-medium tabular-nums" style={{ color: "#bfc3c7" }}>{fmt(hold)}</span>
        <span className="text-xs" style={{ color: "#6a6f75" }}>holding</span>
      </div>
      {sub && <div className="text-[10px] mt-2" style={{ color: "#6a6f75" }}>{sub}</div>}
    </div>
  );
}

export default function BacktestPage() {
  const [data, setData] = useState<Backtest | null>(null);
  const [error, setError] = useState(false);
  const [asset, setAsset] = useState<Asset>("BTC");

  // Days the hash-chained forward ledger has been recording (same source as
  // /track-record). null until loaded — the CTA omits the count rather than
  // showing a made-up number.
  const [ledgerDays, setLedgerDays] = useState<number | null>(null);

  useEffect(() => {
    fetch("/backtest.json", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((j: Backtest) => setData(j))
      .catch(() => setError(true));

    fetch("/forward_ledger.jsonl", { cache: "no-store" })
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
      .then((text) => {
        const lines = text.split("\n").filter(Boolean);
        if (lines.length < 2) return;
        const first = JSON.parse(lines[0]) as { bar_ts?: string };
        const last = JSON.parse(lines[lines.length - 1]) as { bar_ts?: string };
        if (!first.bar_ts || !last.bar_ts) return;
        setLedgerDays(Math.max(1, Math.round((Date.parse(last.bar_ts) - Date.parse(first.bar_ts)) / 86_400_000)));
      })
      .catch(() => {});
  }, []);

  const a = data?.assets[asset];

  const eqDomain = useMemo<[number, number]>(() => {
    if (!a) return [0.5, 25];
    const vals = a.curve.flatMap((p) => [p.s, p.h]).filter((v) => v > 0);
    return [Math.max(0.1, Math.min(...vals) * 0.85), Math.max(...vals) * 1.15];
  }, [a]);

  const yearlyData = useMemo(() => {
    if (!a) return [];
    const years = Array.from(new Set([...Object.keys(a.yearly.strat), ...Object.keys(a.yearly.hold)])).sort();
    return years.map((y) => ({ year: y, strat: (a.yearly.strat[y] ?? 0), hold: (a.yearly.hold[y] ?? 0) }));
  }, [a]);

  return (
    <div className="space-y-10 pb-16">
      <header className="space-y-3">
        <h1 className="text-4xl font-bold tracking-tight" style={{ color: TEXT }}>Backtest & Historical Performance</h1>
        <p className="text-sm max-w-3xl" style={{ color: "#bfc3c7" }}>
          A <strong style={{ color: TEXT }}>walk-forward out-of-sample</strong> backtest across ~6 years of 4-hour data.
          Each fold trades only on data <em>after</em> its training window — there is no peeking at the future.
          That is the opposite of curve-fitting, and it is why these numbers should survive contact with live markets.
        </p>
        {/* Audit finding #29: this page previously asserted "no fitted parameters"
            over figures produced by a walk-forward that re-selects the best spec
            on every training fold. The parameter-free property belongs to the
            deployed ensemble, not to those figures. Say which model is which
            rather than borrowing one model's virtue for another's numbers. */}
        <p className="text-sm max-w-3xl" style={{ color: "#bfc3c7" }}>
          <strong style={{ color: TEXT }}>Which model is this?</strong> The vaults run the{" "}
          <strong style={{ color: TEXT }}>continuous parameter ensemble</strong>: target exposure is the average
          long/flat vote across the <em>entire</em> trend + volatility-gate family — no single spec is chosen — and
          that vote is passed through hysteresis before it is signed on-chain. Because nothing is selected, the
          ensemble has no fitted parameters and in-sample equals out-of-sample by construction. Where a table below
          is labelled as fold-selected, its parameters <em>were</em> chosen per fold, so read it as a test of the
          rule family rather than as the deployed model&apos;s record.
        </p>
      </header>

      {error && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6 text-sm" style={{ color: "#eaeaea" }}>
          Couldn&apos;t load <code className="text-xs">/backtest.json</code> — retry shortly.
        </div>
      )}

      {/* Honest decomposition — the most important section */}
      <section className="rounded-2xl border p-6 space-y-3" style={{ borderColor: `${GOLD}55`, background: `${GOLD}0d` }}>
        <h2 className="text-lg font-semibold" style={{ color: GOLD }}>Where the edge comes from — read this first</h2>
        <p className="text-sm leading-relaxed" style={{ color: "#eaeaea" }}>
          The strategy&apos;s advantage is <strong style={{ color: TEXT }}>drawdown reduction</strong>, not a magic return.
          It stays invested in uptrends and rotates to cash in downtrends, so it sidesteps the worst of each crash —
          across every asset it cut the maximum loss roughly in half. That is the &ldquo;profit&rdquo; you see in the
          live tracker: when the asset falls and the strategy is in cash, it is <em>ahead by the loss it avoided</em>,
          not by trading gains.
        </p>
        <p className="text-sm leading-relaxed" style={{ color: "#eaeaea" }}>
          On <strong style={{ color: TEXT }}>absolute return</strong> the picture is honest and mixed: out-of-sample,
          BTC, ETH and SOL also <em>beat</em> holding, while <strong style={{ color: TEXT }}>XRP underperformed holding
          on return</strong> and won only on drawdown. No leverage, no shorts — so in a straight parabolic bull run,
          simply holding can win. We show every asset, including the one where we lose.
        </p>
      </section>

      {/* Asset tabs */}
      <div className="flex flex-wrap gap-2">
        {ASSETS.map((x) => (
          <button
            key={x}
            onClick={() => setAsset(x)}
            className="px-5 py-2 rounded-xl text-sm font-semibold uppercase tracking-wider transition-all"
            style={asset === x
              ? { background: GOLD, color: "#0b0b0d" }
              : { background: "rgba(255,255,255,0.04)", color: "#bfc3c7", border: "1px solid rgba(255,255,255,0.1)" }}
          >
            {x}
          </button>
        ))}
      </div>

      {a && (
        <>
          <div className="text-xs" style={{ color: "#bfc3c7" }}>
            Out-of-sample {a.oosStart} → {a.oosEnd} · {a.nFolds} folds · avg exposure {(a.avgExposure * 100).toFixed(0)}%
            (in market) · spec <code>{a.frozenSpec}</code> · {data?.costBpsPerSide} bps/side costs
          </div>

          {/* Metric cards */}
          <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <MetricCard label="Max Drawdown" strat={a.strategy.maxDd} hold={a.hold.maxDd} fmt={(n) => fmtPct(n, 0)} betterHigh sub={`${a.drawdownWins}/${a.nFolds} folds shallower than holding`} />
            <MetricCard label="CAGR (annualized)" strat={a.strategy.cagr} hold={a.hold.cagr} fmt={(n) => fmtPct(n, 0)} betterHigh />
            <MetricCard label="Sortino (downside risk-adj.)" strat={a.strategy.sortino} hold={a.hold.sortino} fmt={(n) => n.toFixed(2)} betterHigh />
            <MetricCard label="Calmar (return / max DD)" strat={a.strategy.calmar} hold={a.hold.calmar} fmt={(n) => n.toFixed(2)} betterHigh />
          </section>

          {/* In coin terms — stack sats. The vaults are denominated in the
              underlying, so the benchmark is "did you end with more of the coin",
              not a USD return. sats = strategy ÷ holding (flat 1.0 = simply holding). */}
          <section className="space-y-3">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>In {asset} terms — did a share end with more {asset}?</h3>
            <p className="text-sm" style={{ color: "#bfc3c7" }}>
              The vault is denominated in {asset}, so the honest benchmark is units of the coin, not dollars.
              A flat line at 1.0 is simply holding {asset}; above 1.0 means a share ended the out-of-sample
              window worth <em>more</em> {asset} than buy-and-hold — by stepping to cash in downturns and
              rebuying lower. This is a hypothetical OOS backtest, not a live deposit return.
            </p>
            <div className="grid grid-cols-3 gap-4">
              <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-5">
                <div className="text-[11px] uppercase tracking-wider mb-2" style={{ color: "#6a6f75" }}>{asset} vs holding</div>
                <div className="text-2xl font-bold tabular-nums" style={{ color: a.sats.satsVsHold >= 0 ? "#34d399" : RED }}>{fmtPct(a.sats.satsVsHold, 1)}</div>
                <div className="text-[10px] mt-1" style={{ color: "#6a6f75" }}>a share ended worth {a.sats.endSats.toFixed(2)}× the coin</div>
              </div>
              <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-5">
                <div className="text-[11px] uppercase tracking-wider mb-2" style={{ color: "#6a6f75" }}>Worst drawdown in {asset}</div>
                <div className="text-2xl font-bold tabular-nums" style={{ color: TEXT }}>{fmtPct(a.sats.maxDdSats, 0)}</div>
                <div className="text-[10px] mt-1" style={{ color: "#6a6f75" }}>deepest dip in coin-per-share vs its own peak</div>
              </div>
              <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-5">
                <div className="text-[11px] uppercase tracking-wider mb-2" style={{ color: "#6a6f75" }}>Time ahead of holding</div>
                <div className="text-2xl font-bold tabular-nums" style={{ color: TEXT }}>{fmtPct(a.sats.pctTimeAhead, 0)}</div>
                <div className="text-[10px] mt-1" style={{ color: "#6a6f75" }}>share of the OOS window with more coin than holding</div>
              </div>
            </div>
            <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-4">
              <ResponsiveContainer width="100%" height={240}>
                <LineChart data={a.sats.curve} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" />
                  <XAxis dataKey="t" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} minTickGap={48} />
                  <YAxis domain={["auto", "auto"]} tickFormatter={(v) => `${Number(v).toFixed(2)}×`} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown) => [`${Number(v).toFixed(3)}× ${asset}`, "Coin per share"]) as never}
                  />
                  <ReferenceLine y={1} stroke={GRAY} strokeDasharray="4 4" label={{ value: `Hold ${asset}`, fill: "rgba(234,234,234,0.45)", fontSize: 11, position: "insideTopLeft" }} />
                  <Line type="monotone" dataKey="x" stroke={GOLD} dot={false} strokeWidth={2} isAnimationActive={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Equity curve */}
          <section className="space-y-2">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Growth of $1 — out-of-sample (log scale)</h3>
            {/* Numeric heights: ResponsiveContainer height="100%" measures -1×-1
                in recharts 3.8 here ("width(-1) and height(-1)... greater than 0")
                and all three charts rendered EMPTY in production. */}
            <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-4">
              <ResponsiveContainer width="100%" height={348}>
                <LineChart data={a.curve} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" />
                  <XAxis dataKey="t" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} minTickGap={48} />
                  <YAxis scale="log" domain={eqDomain} tickFormatter={fmtX} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown, n: unknown) => [fmtX(Number(v)), n === "s" ? "Strategy" : "Holding"]) as never}
                  />
                  <Legend formatter={(v) => (v === "s" ? "Strategy" : "Holding")} wrapperStyle={{ fontSize: 12 }} />
                  <Line type="monotone" dataKey="h" stroke={GRAY} dot={false} strokeWidth={1.5} isAnimationActive={false} />
                  <Line type="monotone" dataKey="s" stroke={GOLD} dot={false} strokeWidth={2} isAnimationActive={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Underwater / drawdown */}
          <section className="space-y-2">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Drawdown — how deep underwater (the real edge)</h3>
            <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-4">
              <ResponsiveContainer width="100%" height={268}>
                <AreaChart data={a.drawdown} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" />
                  <XAxis dataKey="t" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} minTickGap={48} />
                  <YAxis tickFormatter={(v) => `${(v * 100).toFixed(0)}%`} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown, n: unknown) => [fmtPct(Number(v), 1), n === "s" ? "Strategy" : "Holding"]) as never}
                  />
                  <Legend formatter={(v) => (v === "s" ? "Strategy" : "Holding")} wrapperStyle={{ fontSize: 12 }} />
                  <Area type="monotone" dataKey="h" stroke={RED} fill={`${RED}22`} strokeWidth={1.2} isAnimationActive={false} />
                  <Area type="monotone" dataKey="s" stroke={GOLD} fill={`${GOLD}33`} strokeWidth={1.6} isAnimationActive={false} />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Per-year returns */}
          <section className="space-y-2">
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Calendar-year returns — strategy vs holding</h3>
            <div className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-4">
              <ResponsiveContainer width="100%" height={268}>
                <BarChart data={yearlyData} margin={{ top: 10, right: 16, bottom: 0, left: 0 }}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" vertical={false} />
                  <XAxis dataKey="year" tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} />
                  <YAxis tickFormatter={(v) => `${(v * 100).toFixed(0)}%`} tick={{ fill: "rgba(234,234,234,0.4)", fontSize: 11 }} width={48} />
                  <Tooltip
                    contentStyle={{ background: "#12141a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, color: TEXT }}
                    formatter={((v: unknown, n: unknown) => [fmtPct(Number(v), 1), n === "strat" ? "Strategy" : "Holding"]) as never}
                  />
                  <Legend formatter={(v) => (v === "strat" ? "Strategy" : "Holding")} wrapperStyle={{ fontSize: 12 }} />
                  <ReferenceLine y={0} stroke="rgba(255,255,255,0.2)" />
                  <Bar dataKey="hold" fill={GRAY} radius={[2, 2, 0, 0]} isAnimationActive={false} />
                  <Bar dataKey="strat" fill={GOLD} radius={[2, 2, 0, 0]} isAnimationActive={false} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Cost sensitivity */}
          {a.costSensitivity.length > 0 && (
            <section className="space-y-2">
              <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Cost sensitivity — does the edge survive fees?</h3>
              <p className="text-xs max-w-3xl" style={{ color: "#bfc3c7" }}>
                We model {data?.costBpsPerSide} bps per side. The downside-risk edge (strategy Sortino minus holding)
                is real at realistic costs but erodes as fees climb — shown honestly so you can judge the margin.
              </p>
              <div className="overflow-x-auto rounded-2xl border border-[#2a2f3a]">
                <table className="w-full min-w-[560px] text-xs tabular-nums">
                  <thead>
                    <tr className="border-b border-[#2a2f3a] text-left" style={{ color: "#bfc3c7" }}>
                      {["Cost (bps/side)", "Strategy Sortino", "Holding Sortino", "Strategy CAGR", "Strategy max DD"].map((h) => (
                        <th key={h} className="px-4 py-3 font-medium uppercase tracking-wider">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody style={{ color: "#eaeaea" }}>
                    {a.costSensitivity.map((r) => {
                      const live = r.bps === (data?.costBpsPerSide ?? 5);
                      return (
                        <tr key={r.bps} className="border-b border-white/5" style={live ? { background: `${GOLD}14` } : undefined}>
                          <td className="px-4 py-2.5">{r.bps}{live ? "  ← modeled" : ""}</td>
                          <td className="px-4 py-2.5" style={{ color: r.stratSortino >= r.holdSortino ? "#34d399" : RED }}>{r.stratSortino.toFixed(2)}</td>
                          <td className="px-4 py-2.5">{r.holdSortino.toFixed(2)}</td>
                          <td className="px-4 py-2.5">{fmtPct(r.stratCagr, 0)}</td>
                          <td className="px-4 py-2.5">{fmtPct(r.stratMaxDd, 0)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </section>
          )}

          {/* Methodology */}
          <section className="rounded-2xl border border-[#2a2f3a] bg-[#1c1c21] p-6 space-y-2 text-sm" style={{ color: "#bfc3c7" }}>
            <h3 className="text-lg font-semibold" style={{ color: TEXT }}>Methodology & honest disclaimers</h3>
            <ul className="list-disc list-inside space-y-1.5">
              <li><strong style={{ color: TEXT }}>Walk-forward OOS:</strong> {a.nFolds} folds; every trade is on out-of-sample data after its training window.</li>
              <li><strong style={{ color: TEXT }}>Deployed model — no fitted parameters:</strong> exposure = mean long/flat vote over the whole trend+vol-gate grid, quantized to 25%, then passed through hysteresis before it is signed on-chain. Nothing is selected, so there is nothing to over-fit. We deliberately do <em>not</em> hyper-optimize — that&apos;s how backtests lie.</li>
              <li><strong style={{ color: TEXT }}>Where the figures come from:</strong> the frozen spec shown above each chart names the model that produced that panel. A fold-selected spec is a study of the rule family; only the ensemble figures describe what the vault does. If the two disagree, the ensemble is the one that matters.</li>
              <li><strong style={{ color: TEXT }}>Spot, long/flat only:</strong> no leverage, no shorts. Returns are in the underlying asset.</li>
              <li><strong style={{ color: TEXT }}>Costs:</strong> {data?.costBpsPerSide} bps per side modeled; see the cost-sensitivity table for the margin of safety.</li>
              <li><strong style={{ color: TEXT }}>Not a guarantee:</strong> a backtest is not live performance. Crypto can draw down {">"}40% even here. Past results do not predict the future.</li>
            </ul>
          </section>
        </>
      )}

      {/* Conversion CTA — the proof continues live, not just in history */}
      <section
        className="rounded-2xl border p-8 text-center space-y-4"
        style={{ borderColor: `${GOLD}55`, background: `${GOLD}0d` }}
      >
        <h2 className="text-xl font-semibold" style={{ color: TEXT }}>
          This isn&apos;t just history
        </h2>
        <p className="text-sm max-w-2xl mx-auto leading-relaxed" style={{ color: "#bfc3c7" }}>
          This exact strategy family is running live right now — a hash-chained paper record
          {ledgerDays !== null ? ` (day ${ledgerDays})` : ""} and an autonomous on-chain vault on testnet.
        </p>
        <div className="flex flex-wrap justify-center gap-3 pt-1">
          <Link
            href="/track-record"
            className="px-6 py-3 rounded-xl text-sm font-semibold transition-all hover:scale-[1.02]"
            style={{ background: GOLD, color: "#0b0b0d" }}
          >
            View the live track record
          </Link>
          <Link
            href="/vaults/spot"
            className="px-6 py-3 rounded-xl text-sm font-semibold transition-all hover:scale-[1.02]"
            style={{ border: `1px solid ${GOLD}88`, color: GOLD }}
          >
            Open the testnet vault
          </Link>
        </div>
      </section>
    </div>
  );
}
